server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://powerline-1-load-balancer-932684365.eu-north-1.elb.amazonaws.com:94