server:
  port: 8088

spring:
  profiles:
    active: native


  config:
    activate:
      on-profile: "dev"

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%blue(%d{YYYY:MM:dd:HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}