spring:
  application:
    name: "config-server"

  profiles:
    active: git


  cloud:
    config:
      server:
        git:
          uri: https://github.com/Barreltech/config-server.git/
          default-label: main
          timeout: 50
          clone-on-start: true
          force-pull: true
          username: barreltechlimited@gmail.com
          password: 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

server:
  port: 8088


logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%blue(%d{YYYY:MM:dd:HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}