server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://powerline-1-load-balancer-932684365.eu-north-1.elb.amazonaws.com:85

management:
  tracing:
    sampling:
      probability: 1.0